Repository chez14/node-mal-api, pull requests merged in 2020-08, with the labels that each got.

#1 Publish to NPM
  README.md
  jest.config.js
  package.json
  packages/mal-api-lite/README.md
  packages/mal-api-lite/__tests__/mal-api-lite.test.ts
  packages/mal-api-lite/lib/MALClient.ts
  packages/mal-api-lite/package.json
  yarn.lock
Labels: major

#3 Migrate from tslint to eslint + @typescript-eslint
  .eslintignore
  .eslintrc.json
  .gitignore
  package.json
Labels: skip-release, tests

#4 Lint configuration
  .eslintignore
  .github/workflows/release.yml
  .github/workflows/test.yml
  package.json
  packages/mal-api-lite/__tests__/mal-api-lite.test.ts
  packages/mal-api-lite/lib/MALClient.ts
  packages/mal-api-lite/lib/RequestInterface.ts
  tslint.json
  yarn.lock
Labels: internal
